# -*- coding: utf-8 -*-
"""helloworld.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10We-bCLc-93y4x-bawXtyHTYR-LNrwbG

## Question 1. Check Python Version
"""

!python --version

"""## Question 2. Perform Operation Using the Operands 2 and 4"""

print(3 + 2)   # addition(+)

print(3 - 2)   # subtraction(-)

print(3 * 2)   # multiplication(*)

print(3 / 2)   # division(/)

print(3 ** 2)  # exponential(**)

print(3 % 2)   # modulus(%)

print(3 // 2)  # Floor division operator(//)

"""## Question 3. Write the Following Strings"""

print('James') #My Name

print('Williams') # Family Name

print('Nigeria') #Country

print('I am engoying 30 days of Python')

"""## Question 4. Check Data Types"""

print(type(10))                  # Int

print(type(9.8))                # Float

print(type(3.14))             # Float

print(type(4-4j))             #Complex number

print(type(['Asbeneh', 'Python', 'Finland']))     #List

print(type('James'))        #Str

print(type('Williams'))     #Str

print(type('Nigeria'))      #Str