# -*- coding: utf-8 -*-
"""ModuleOperators.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WoiYS-ncsw_BkVozlj5_TFijoB17G2AY

# James Williams Solution to assignment

# Excercise Module 3
"""

#1
Age = 35

#2
height = 1.89 #meters

#3
Complex_num = 2 + 3j

#4
trian_base = int(input('Enter Triangle base lenght:' ))
trian_height = int(input('Enter Triangle heigth lenght:'))
Trian_area = 0.5 * trian_base * trian_height
print('Area of the Triangle is: ', Trian_area)

#5
trian_a = int(input('Enter a side of Triangle :' ))
trian_b = int(input('Enter b side of Triangle :' ))
trian_c = int(input('Enter c side of Triangle :' ))
trian_perimeter = trian_a + trian_b + trian_c
print('Perimeter of Triangle: 'trian_perimeter)

#6
rect_length = int(input('Enter lenght of rectangle :' ))
rect_width = int(input('Enter width of rectangle :', ))
rect_area = 2 * rect_length * rect_width
print('Area of rectangle: 'rect_area)

#7
PI = 3.14
radius = int(input('Enter radius of circle:' ))
cir_area = 2 * PI * radius
print('Area of the circle: ', round(cir_area,2))

#8
x = 1
y = 2*x - 2
slope_a = y/x
print('SLope to the value:, 'round(slope_a,2))

#9
x_distance = [2,2]
y_distance = [6,10]
y = y_distance[1] - y_distance[0]
x = x_distance[1] - x_distance[0]
slope_b = y/(x+0.00001)
print('Slope for the distance is:', round(slope_b,2))

euclid_distance = (y ** 2 + x ** 2) ** 0.5
print("Euclidean Distance: "round(euclid_distance,2))

#10
print('Is slope_a greater than slope_b : ', slope_a > slope_b)
print('Is slope_a less than slope_b : ', slope_a < slope_b)
print('Is slope_a equal slope_b : ', slope_a == slope_b)

#11
for x in range(-12, 12):
  y = x**2 + 6*x + 9
  print('y : ', y, '- x :', x)
  if y == 0:
    print('at x =', x, ': y = 0')

#12
print('Is len python > dragon: ', len('python') > len('dragon'))
print('Is len python < dragon: ', len('python') < len('dragon'))
print('Is len python == dragon: ', len('python') == len('dragon'))

#13
print('is "on" in "python" and "dragon"', 'on' in 'python' and 'on' in 'dragon')

#14
print('Is jargon in the sentence ? ', 'jargon' in 'I hope this course is not full of jargon')

#15
print('Is "on" in both "words"', 'on' in 'python' and 'on' in 'dragon')

#16
str(float(len('python')))

#17

x = 5
print('x is odd number', x%2 != 0 )

#18

print('Is 7//3 equal to 2.7 ', 7//3 == 2.7)

#19
print('is type "10" equals type 10 ? ', type('10') == type(10))

#20
print('is int(9.8) equals to 10 ? ', int(float('9.8')) == 10)
3
#21
hour = int(input('Enter hours:'))
rate = int(input('Enter rate per hour:'))
print('Your weekly earning is: ', hour * rate)

#22
years = int(input('Enter number of years you have lived:'))
print('You have lived for ', years * 3153600000, 'seconds')

#23
for m in range(1,6):
  print(m, end=' ')
  for x in range(0,4):
    print(m**x, end=' ')
  print('')