# -*- coding: utf-8 -*-
"""Strings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DAnUd2eTPSVdpD7nqNmiJNAQtGle_NP4

#Exercise Module 4
"""

#1. Catenate String

print('Thirty ' + 'Days ' + 'Or ' + 'Python ')

#2. Catenate string

print('Coding '+'For '+'All')

#3. Declare variable
company = 'Coding For All'

#4. print variable
print(company)

#5. string len
print(len(company))
print(company)

#6. uppercase
print(company.upper())

#7. lowercase
print(company.lower())

#8. capitalized
print(company.capitalize())
print(company.swapcase())

#9. cut
print(company[0:5])

#10 index
print(company.index('Coding'))

#11. Replace.
print(company.replace('Coding','Python'))

#12. change
print('Python for Everyone'.replace('Everyone','All'))

#13.split
print(company.split(' '))

#14.split_2
print('Facebook, Google, Microsoft, Apple, IBM, Oracle, Amazon'.split(','))

#15.first index
print('Coding for All'[0])

#16.last index
print('Coding for All'[-1])

#17.character index
print('Coding For All'[10])   #white space

#18. Acronym

#19.

#20.
print('Coding For All'.find('C'))

#21.
print('Coding For All'.find('F'))

#22. rfind
print('Coding For All'.rfind('l'))

#23.
print('you cannot end a sentence with because because because is a conjuction'.index('because'))

#24
print('you cannot end a sentence with because because because is a conjuction'.rindex('because'))

#25.
print('you cannot end a sentence with because because because is a conjuction'.find(' is')) #54
print('you cannot end a sentence with because because because is a conjuction'[31:54])

#26
print('You cannot end a sentence with because because because is a conjuction'.find('because'))

#27.
print('you cannot end a sentence with because because because is a conjuction'.find(' is')) #54
print('you cannot end a sentence with because because because is a conjuction'[31:54])

#28.
print('Coding For All'.startswith('Coding'))

#29.
print('Coding For All'.endswith('coding'))

#30.
print(' Coding For All '.strip())

#31.
print('30DayOfPython'.isidentifier())

#32.
print('thirty_days_of_python'.isidentifier())

#33.
print('I\nam\nenjoying\nthis\nchallenge')
print('I\njust\nwonder\nwhat\nis\nnext')

#34.
print('Name\t Age\t Country\t City')
print('Aabeneh\t 250\t Finland\t Helsinki')

#35.
radius = 10
area = 3.14 * radius ** 2
print(f'The area of a circle with {radius} is {area:.2f} meters square')

#36.
print('8 + 6 = {0}'.format(8+6))
print('8 - 6 = {0}'.format(8-6))
print('8 * 6 = {0}'.format(8*6))
print('8 / 6 = {:.2f}'.format(8/6))
print('8 % 6 = {0}'.format(8%6))
print('8 // 6 = {0}'.format(8//6))
print('8 ** 6 = {0}'.format(8**6))