# -*- coding: utf-8 -*-
"""Tuples.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lQa3soBwbkeuVoVm_LNNYO5zkf_cNlVM
"""

# Tuple Exercises

# Level 1

#1.
empty_tuple = tuple()

#2.
brothers = ('Michael', 'Wellington', 'Zaminathan')
sisters = ('Yetunde', 'Ronke', 'Olivia')

#3.
siblings = brothers + sisters

#4.
print('My siblings are:', len(siblings))

#5.
family_members = siblings + ('James snr.', 'Folashade')
print('Family members: ', family_members)

"""#Exercise: Level 2"""

#1.
brother_01, brother_02, brother_03, sister_01, sister_02, sister_03, *parents = family_members
print(parents)

#2.
fruits = ('mango', 'apples', 'pineapple')
vegetables = ('carrot', 'brocolli', 'lettuce')
animal_products = ('milk', 'honey', 'whale oil')

#3.
food_stuff_tp = fruits + vegetables + animal_products

#4.
print(food_stuff_tp[(len(food_stuff_tp)//2)])

#5.
print(food_stuff_tp[:3])

#6.
del food_stuff_tp

#7.
nordic_countries = ('Denmark', 'Finland','Iceland', 'Norway', 'Sweden')

print('Is Estonia present in country:', 'Estonia' in nordic_countries)

print('Is Estonia present in country:', 'Iceland' in nordic_countries)